"""Regenerate demo/semgeozev2.py — a dependency-free single-file build of the model.

A HuggingFace Space should not need the repo's import chain, open3d, or a GPU. This concatenates
the parts of `semseg/` the Space actually runs (metrics, segment helpers, the neighbour graph, the
model) into one module, stripping the intra-package imports.

Edit `semseg/`, never `demo/semgeozev2.py`, then re-run:

    python demo/pack_space.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'demo', 'semgeozev2.py')

HEADER = '''"""SemGeoZe v2, packed into one file for the HuggingFace Space.

GENERATED by demo/pack_space.py from semseg/ — do not edit here, edit the package and re-pack.
The Space needs no repo import chain, no open3d and no GPU: the geometry pre-pass (normals,
FPFH, VCCS) is baked into the shipped .npz files.
"""
import numpy as np
import torch
import torch.nn.functional as F
from torch import nn

from serialization import encode
'''

COLORS = '''
# ScanNet's own 20-class colormap.
SCANNET_COLORS = [
    (174, 199, 232), (152, 223, 138), (31, 119, 180), (255, 187, 120), (188, 189, 34),
    (140, 86, 75), (255, 152, 150), (214, 39, 40), (197, 176, 213), (148, 103, 189),
    (196, 156, 148), (23, 190, 207), (247, 182, 210), (219, 219, 141), (255, 127, 14),
    (158, 218, 229), (44, 160, 44), (112, 128, 144), (227, 119, 194), (82, 84, 163)]
'''


def read(rel):
    return open(os.path.join(ROOT, rel)).read()


def strip(s):
    """Drop intra-repo imports, sys.path juggling and the module docstring."""
    s = re.sub(r'\A"""(?:.|\n)*?"""\n', '', s)
    keep = []
    for line in s.split('\n'):
        if re.match(r'^\s*(from semseg|import sys|import os|sys\.path|from serialization|'
                    r'import numpy|import torch|from torch|import re)\b', line):
            continue
        keep.append(line)
    return '\n'.join(keep).strip('\n')


def section(title, body):
    return f'\n\n# {"-" * 74}\n#  {title}\n# {"-" * 74}\n\n{body}\n'


def main():
    parts = [HEADER]
    parts.append(section('metrics', strip(read('semseg/metrics.py'))))

    bp = read('semseg/semmodel/best_param.py')
    names = bp[bp.index('SCANNET20 = ['):bp.index(']', bp.index('SCANNET20 = [')) + 1]
    parts.append(section('class names and colours', names + '\n' + COLORS.strip()))

    parts.append(section('segment helpers', strip(read('semseg/semmodel/common.py'))))

    curve = strip(read('semseg/semmodel/curve.py'))
    curve = curve[curve.index('ORDERS ='):]
    parts.append(section('neighbour graph', curve))

    model = strip(read('semseg/semmodel/semgeozev2.py'))
    model = model[model.index('# ---'):]
    parts.append(section('model', model))

    src = ''.join(parts)
    compile(src, OUT, 'exec')                      # fail loudly rather than ship a broken Space
    open(OUT, 'w').write(src)
    print(f'wrote {OUT}  ({len(src.splitlines())} lines)')
    print('reminder: demo/serialization/ must be copied alongside it')


if __name__ == '__main__':
    sys.exit(main())
